version: "3.8"
services:
  postgres-database:
    image: postgres:latest
    container_name: postgres-quiz
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-db:/var/lib/postgresql/data

  quizloom-production:
    image: quizloom
    container_name: quizloom-production-test
    env_file: .env.production
    ports:
      - "5001:5001"
    stdin_open: true
    tty: true

volumes:
  postgres-db:
